Lo primero que hacemos es cargar todos las hojas a utilizar para posteriormente concatenarlos

In [91]:
import pandas as pd
from pathlib import Path

# 1. Define la ruta de la carpeta (utilizando la ruta proporcionada)
ruta_carpeta = Path(r'C:\Users\scalz\Documents\Documentos\Lab_Datos\TPfinal\Archivos_xlsx')

# 2. Encuentra la lista de archivos CSV dentro de esa carpeta
archivos_csv = list(ruta_carpeta.glob('*.csv'))

if not archivos_csv:
    print("⚠️ ¡Atención! No se encontraron archivos CSV en la carpeta. Verifica que la extensión sea .csv.")
else:
    # 3. Lee cada archivo CSV y crea una lista de DataFrames
    print(f"Archivos CSV encontrados: {len(archivos_csv)}")
    lista_dataframes = [pd.read_csv(archivo) for archivo in archivos_csv]

    # 4. CONCATENACIÓN HORIZONTAL: Une todos los DataFrames por COLUMNAS
    df_combinado_horizontal = pd.concat(
        lista_dataframes, 
        axis=1,             # <--- ESTE ES EL CAMBIO CLAVE: Une por columnas.
        join='outer'        # Por defecto, usa 'outer' (mantiene todas las filas), pero con filas iguales 'inner' u 'outer' dan el mismo resultado.
    )

    # 5. Verificación Final
    print("\n✅ Concatenación horizontal completada.")
    
    # El número de filas debería ser el mismo que el de cualquier archivo original.
    print(f"Número de filas (filas originales): {df_combinado_horizontal.shape[0]}") 
    
    # El número de columnas es la suma de las columnas de todos los archivos originales.
    print(f"Número de columnas totales (sumatoria de columnas de todos los CSVs): {df_combinado_horizontal.shape[1]}") 
    
    print("\nDataFrame Combinado (Primeras filas y todas las columnas):")
    print(df_combinado_horizontal.head())

Archivos CSV encontrados: 6

✅ Concatenación horizontal completada.
Número de filas (filas originales): 16054
Número de columnas totales (sumatoria de columnas de todos los CSVs): 137

DataFrame Combinado (Primeras filas y todas las columnas):
                   DIA      HORA  Agua Planta (Hl)  Agua Elaboracion (Hl)  \
0  2021-07-01 00:00:00  00:00:00               0.0                    0.0   
1  2021-07-01 00:00:00  01:00:00               0.0                    0.0   
2  2021-07-01 00:00:00  02:00:00             490.0                   28.0   
3  2021-07-01 00:00:00  03:00:00             650.0                   52.0   
4  2021-07-01 00:00:00  04:00:00             880.0                   75.0   

   Agua Bodega (Hl)  Agua Cocina (Hl)  Agua Dilucion (Hl)  Agua Envasado (Hl)  \
0               0.0               0.0                 0.0                 0.0   
1               0.0               0.0                 0.0                 0.0   
2              28.0               0.0             

In [92]:
df1=df_combinado_horizontal.copy()

In [93]:
# 1. Define la ruta de la carpeta (utilizando la ruta proporcionada)
ruta_carpeta = Path(r'C:\Users\scalz\Documents\Documentos\Lab_Datos\TPfinal\Archivos_xlsx2')

# 2. Encuentra la lista de archivos CSV dentro de esa carpeta
archivos_csv = list(ruta_carpeta.glob('*.csv'))

if not archivos_csv:
    print("⚠️ ¡Atención! No se encontraron archivos CSV en la carpeta. Verifica que la extensión sea .csv.")
else:
    # 3. Lee cada archivo CSV y crea una lista de DataFrames
    print(f"Archivos CSV encontrados: {len(archivos_csv)}")
    lista_dataframes = [pd.read_csv(archivo) for archivo in archivos_csv]

    # 4. CONCATENACIÓN HORIZONTAL: Une todos los DataFrames por COLUMNAS
    df_combinado_horizontal = pd.concat(
        lista_dataframes, 
        axis=1,             # <--- ESTE ES EL CAMBIO CLAVE: Une por columnas.
        join='outer'        # Por defecto, usa 'outer' (mantiene todas las filas), pero con filas iguales 'inner' u 'outer' dan el mismo resultado.
    )

    # 5. Verificación Final
    print("\n✅ Concatenación horizontal completada.")
    
    # El número de filas debería ser el mismo que el de cualquier archivo original.
    print(f"Número de filas (filas originales): {df_combinado_horizontal.shape[0]}") 
    
    # El número de columnas es la suma de las columnas de todos los archivos originales.
    print(f"Número de columnas totales (sumatoria de columnas de todos los CSVs): {df_combinado_horizontal.shape[1]}") 
    
    print("\nDataFrame Combinado (Primeras filas y todas las columnas):")
    print(df_combinado_horizontal.head())

Archivos CSV encontrados: 6

✅ Concatenación horizontal completada.
Número de filas (filas originales): 15649
Número de columnas totales (sumatoria de columnas de todos los CSVs): 137

DataFrame Combinado (Primeras filas y todas las columnas):
                   DIA      HORA  Agua Planta (Hl)  Agua Elaboracion (Hl)  \
0  2022-07-01 00:00:00  02:00:00             466.0                   43.0   
1  2022-07-01 00:00:00  03:00:00             915.0                   86.0   
2  2022-07-01 00:00:00  04:00:00            1364.0                  128.0   
3  2022-07-01 00:00:00  05:00:01            1986.0                  170.0   
4  2022-07-01 00:00:00  06:00:01            2432.0                  213.0   

   Agua Bodega (Hl)  Agua Cocina (Hl)  Agua Dilucion (Hl)  Agua Envasado (Hl)  \
0              43.0               0.0                 0.0                26.0   
1              86.0               0.0                 0.0                52.0   
2             128.0               0.0             

In [94]:
df2=df_combinado_horizontal.copy()

In [95]:
import pandas as pd

# 1. Identificar en df1
columnas_df1 = df1.columns
duplicadas_df1 = columnas_df1[columnas_df1.duplicated()]

print("--- Columnas duplicadas en df1 ---")
if not duplicadas_df1.empty:
    print(duplicadas_df1.tolist())
else:
    print("No se encontraron columnas duplicadas en df1.")

print("\n---------------------------------")

# 2. Identificar en df2
columnas_df2 = df2.columns
duplicadas_df2 = columnas_df2[columnas_df2.duplicated()]

print("--- Columnas duplicadas en df2 ---")
if not duplicadas_df2.empty:
    print(duplicadas_df2.tolist())
else:
    print("No se encontraron columnas duplicadas en df2.")

--- Columnas duplicadas en df1 ---
['DIA', 'HORA', 'DIA', 'HORA', 'DIA', 'HORA', 'DIA', 'HORA', 'DIA', 'HORA']

---------------------------------
--- Columnas duplicadas en df2 ---
['DIA', 'HORA', 'DIA', 'HORA', 'DIA', 'HORA', 'DIA', 'HORA', 'DIA', 'HORA']


In [96]:
vector_df=[df1,df2]

df1 = df1.loc[:, ~df1.columns.duplicated()]
df2 = df2.loc[:, ~df2.columns.duplicated()]


In [97]:
import pandas as pd

# 1. Identificar en df1
columnas_df1 = df1.columns
duplicadas_df1 = columnas_df1[columnas_df1.duplicated()]

print("--- Columnas duplicadas en df1 ---")
if not duplicadas_df1.empty:
    print(duplicadas_df1.tolist())
else:
    print("No se encontraron columnas duplicadas en df1.")

print("\n---------------------------------")

# 2. Identificar en df2
columnas_df2 = df2.columns
duplicadas_df2 = columnas_df2[columnas_df2.duplicated()]

print("--- Columnas duplicadas en df2 ---")
if not duplicadas_df2.empty:
    print(duplicadas_df2.tolist())
else:
    print("No se encontraron columnas duplicadas en df2.")

--- Columnas duplicadas en df1 ---
No se encontraron columnas duplicadas en df1.

---------------------------------
--- Columnas duplicadas en df2 ---
No se encontraron columnas duplicadas en df2.


In [98]:
vector_df=[df1,df2]
df_concatenado = pd.concat(vector_df, ignore_index=True)

In [99]:
# 1. Importar la librería Pandas
import pandas as pd

# Suponiendo que 'mi_dataframe' es el DataFrame que quieres guardar
# mi_dataframe = pd.DataFrame(...)

# 2. Generar y guardar el archivo CSV
nombre_archivo = 'datos_para_descargar.csv'

df_concatenado.to_csv(
    nombre_archivo,
    index=False,      # NO incluir los índices de fila del DataFrame
    encoding='utf-8'  # Usar una codificación estándar que soporte caracteres especiales
)

print(f"✅ Archivo '{nombre_archivo}' creado y listo para descargar en tu directorio actual.")

✅ Archivo 'datos_para_descargar.csv' creado y listo para descargar en tu directorio actual.


A partir de esto comienzo con el EDA. Se viene lo chido agustin MarxSioni(sta)

Lo primero que hago es detrectar valores faltantes


In [100]:
df_concatenado.isnull().sum().sort_values()

Aire Servicios (M3)        142
Vapor L3                   194
Restos Planta (Kw)         199
Agua Elaboracion (Hl)      203
Agua Servicios (Hl)        203
                         ...  
Agua Linea 5/Hl          11494
Aire L5 / Hl             11494
ET Linea 5/Hl            11494
Vapor _Vapor_L5 (KG)     16128
Vapor_L5 (KG)            16387
Length: 128, dtype: int64

In [101]:
import numpy as np
#Lo que quiero hacer es guardar todas las columnas donde los nulos sean mayor a 5000(aprox un 5% del dataset) eliminarlas ya que creo que faltan muchos datos para imputarlas
null_counts = df_concatenado.isnull().sum()
# 2. Filtrar y obtener los nombres de las columnas que cumplen la condición
columnas_con_muchos_nulos = null_counts[null_counts > 5000].index.tolist()

In [102]:
columnas_con_muchos_nulos

['Vapor _Vapor_L5 (KG)',
 'EE Linea 2 / Hl',
 'EE Linea 3 / Hl',
 'Agua Linea 2/Hl',
 'Agua Linea 3/Hl',
 'Agua Linea 5/Hl',
 'ET Linea 2/Hl',
 'ET Linea 3/Hl',
 'ET Linea 5/Hl',
 'Aire L2 / Hl',
 'Aire L3 / Hl',
 'Aire L5 / Hl',
 'Vapor_L5 (KG)']

Faltan datos de TODAS las columnas desde el 16/3/22 hasta el 1/7/22. Que hacemos? las imputamos nomas?

A partir de lo visto yo borraria las 13 columnas donde los valores nulos representan mas del 5% de la cantidad de datos. 
Antes voy a ver que tan correlacionadas estan con la variable objetivo

In [103]:
#Aca lo que hago es eliminar los null en cualquiera de las dos columnas a modo de pruea para solamente ver
#que tan correlacionada estan las columnas que quiero borrar (muchos null) y la objetivo
import numpy as np
import pandas as pd

# Tu bucle original con la modificación
for i in columnas_con_muchos_nulos:
    # Crear un DataFrame temporal con solo las dos columnas
    temp_df = df_concatenado[['Frio (Kw)', i]].copy()

    # **Eliminar las filas donde haya algún NaN en estas dos columnas**
    temp_df_cleaned = temp_df.dropna()
    
    # Comprobar si aún quedan datos para correlacionar
    if len(temp_df_cleaned) > 1: 
        # Calcular la correlación en los datos limpios
        correlacion = np.corrcoef(temp_df_cleaned['Frio (Kw)'], temp_df_cleaned[i])
        print(f"Correlación entre 'Frio (Kw)' y '{i}':")
        print(correlacion)
    else:
        print(f"No hay suficientes datos válidos (después de eliminar NaN) para calcular la correlación entre 'Frio (Kw)' y '{i}'.")

Correlación entre 'Frio (Kw)' y 'Vapor _Vapor_L5 (KG)':
[[1.         0.00119096]
 [0.00119096 1.        ]]
Correlación entre 'Frio (Kw)' y 'EE Linea 2 / Hl':
[[ 1.         -0.00162782]
 [-0.00162782  1.        ]]
Correlación entre 'Frio (Kw)' y 'EE Linea 3 / Hl':
[[ 1.00000000e+00 -1.49440072e-04]
 [-1.49440072e-04  1.00000000e+00]]
Correlación entre 'Frio (Kw)' y 'Agua Linea 2/Hl':
[[ 1.         -0.00139238]
 [-0.00139238  1.        ]]
Correlación entre 'Frio (Kw)' y 'Agua Linea 3/Hl':
[[ 1.00000000e+00 -2.07863676e-04]
 [-2.07863676e-04  1.00000000e+00]]
Correlación entre 'Frio (Kw)' y 'Agua Linea 5/Hl':
[[ 1.        -0.0010289]
 [-0.0010289  1.       ]]
Correlación entre 'Frio (Kw)' y 'ET Linea 2/Hl':
[[ 1.         -0.00130219]
 [-0.00130219  1.        ]]
Correlación entre 'Frio (Kw)' y 'ET Linea 3/Hl':
[[ 1.00000000e+00 -1.62934298e-04]
 [-1.62934298e-04  1.00000000e+00]]
Correlación entre 'Frio (Kw)' y 'ET Linea 5/Hl':
[[ 1.         -0.00104183]
 [-0.00104183  1.        ]]
Correla

Quiero ver por las dudas si no me esta tomando los valores de 0 como valores nulos

In [104]:
import numpy as np
vals=np.where(df_concatenado['EE Linea 2 / Hl']==0)

indices_de_cero = vals[0]

In [105]:
len(indices_de_cero)

4477

In [106]:
print(df_concatenado['EE Linea 2 / Hl'].isnull().sum())
#Como son valores diferentes veo que los valores nulos son diferentes de 0

5612


Lo que voy a hacer ahora es borrar esas 13 columnas (luego se podria aumentar el "umbral" y por ende borrar mas columnas)

In [107]:
for i in columnas_con_muchos_nulos: 
    df_concatenado=df_concatenado.drop(i,axis=1)

Ahora separo el conjunto de datos en train y test. 

In [108]:
import sklearn as skl
y=df_concatenado['Frio (Kw)']
x_train, x_test, y_train, y_test=skl.model_selection.train_test_split(df_concatenado, y, test_size=0.2)

Ahora imputo los valores nulos con knn

In [109]:
imputer=skl.impute.KNNImputer(n_neighbors=10)
x_train=imputer.fit_transform(x_train)
#y_train=imputer.fit_transform(y_train)
x_test=imputer.fit_transform(x_test)
#y_test=imputer.fit_transform(y_test)


ValueError: could not convert string to float: '2022-12-13 00:00:00'

Ahora tambien debo detectar los valores atipicos de cada una de las columnas para posteriormente imputarlos, seguramente con knn

In [ ]:
import pandas as pd

# 1. Definir las fechas de inicio y fin como cadenas
fecha_inicio = '2022-03-16 00:00:00'
fecha_fin = '2022-07-01 00:00:00'

# 2. Generar el rango de fechas con una frecuencia de una hora ('H')
# El resultado es un objeto DatetimeIndex que incluye la fecha de inicio y la fecha de fin.
rango_fechas_completo = pd.date_range(
    start=fecha_inicio, 
    end=fecha_fin, 
    freq='H'
)

# 3. Convertir el rango a un DataFrame de pandas
df_fechas = pd.DataFrame({
    'Fecha_Hora': rango_fechas_completo,
    'ID_Muestra': range(1, len(rango_fechas_completo) + 1)
})

# 4. Exportar el DataFrame a un archivo Excel
nombre_archivo = "fechas_faltantes_completo.xlsx"
df_fechas.to_excel(
    nombre_archivo, 
    index=False, # No incluir el índice de pandas en el archivo
    sheet_name='Rango_Horario'
)

print(f"✅ Archivo '{nombre_archivo}' generado con éxito.")
print(f"El DataFrame contiene {len(df_fechas)} muestras.")

C:\Users\scalz\AppData\Local\Temp\ipykernel_632\1903916467.py:9: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  rango_fechas_completo = pd.date_range(


✅ Archivo 'fechas_faltantes_completo.xlsx' generado con éxito.
El DataFrame contiene 2569 muestras.
